spring:
  application:
    name: PEDIDO-SERVICE

server:
  port: 9093

eureka:
  client:
    fetchRegistry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

