server:
  port: 8761

spring:
  boot:
     admin:
        client:
            url: http://localhost:7777/admin
              
management:
    endpoints:
       web:
          exposure:
              include: "*"
    endpoint:      health:        show-details: always
        
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
