spring:
  application:
    name: PRODUTO-SERVICE
  boot:
     admin:
        client:
            url: http://localhost:7777/admin
              
management:
    endpoints:
       web:
          exposure:
              include: "*"
    endpoint:
      health:
        show-details: always

server:
  port: 9091

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
