spring:
  application:
    name: API-INTELIGENTE-ZUUL
  boot:
     admin:
        client:
            url: http://localhost:7777/admin
              
management:
    endpoints:
       web:
          exposure:
              include: "*"
    endpoint:
      health:
        show-details: always
        
server:
  port: 9090

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    produto-service:
       path: /produtos/**
       serviceId: PRODUTO-SERVICE
    pedido-service:
       path: /pedidos/**
       serviceId: PEDIDO-SERVICE
  host:
    connect-timeout-millis: 50000
    socket-timeout-millis: 600000      
    
ribbon:
     ConnectTimeout: 1000000
     ReadTimeout: 1000000
    
