spring:
  application:
    name: API-INTELIGENTE-ZUUL

server:
  port: 9090

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    produto-service:
       path: /produtos/**
       serviceId: PRODUTO-SERVICE
    pedido-service:
       path: /pedidos/**
       serviceId: PEDIDO-SERVICE
  host:
    socket-timeout-millis: 30000    
       