spring:
  application:
    name: API-GATEWAY
  boot:
     admin:
        client:
            url: http://localhost:7777/admin
              
management:
    endpoints:
       web:
          exposure:
              include: "*"
    endpoint:
      health:
        show-details: always

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    transacoes-financeiras-service:
       path: /transacoes/**
       serviceId: TRANSACOES-FINANCEIRAS-SERVICE
    transacoes-persistencia-service:
       path: /persistencia/**
       serviceId: TRANSACOES-PERSISTENCIA-SERVICE
  host:
    socket-timeout-millis: 30000
