spring:
  application:
    name: TRANSACOES-PERSISTENCIA-SERVICE
  datasource:
      url: jdbc:mysql://localhost:3306/dbtransacoes?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: shtkal
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database: mysql
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
          kafka-send-in:
            destination: transacoes
            contentType: application/json
          kafka-send-out:
            destination: transacoes
            contentType: application/json   
  kafka:
    consumer:
      auto-offset-reset: earliest

server:
  port: 6262

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

